base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
  builder:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.20-openshift-4.14
build_root:
  from_repository: true
images:
  - dockerfile_path: Dockerfile
    from: cli
    inputs:
      builder:
        as:
          - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.14
    to: odf-must-gather
releases:
  initial:
    integration:
      name: "4.14"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.14"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
  - as: some
    commands: test -e /usr/bin/gather || exit 1
    container:
      from: odf-must-gather
zz_generated_metadata:
  branch: main
  org: red-hat-storage
  repo: odf-must-gather
